# General config
    config-version = 2
    start-at-login = true

# Workspace / Monitor Assignment
    [workspace-to-monitor-force-assignment]
    1 = 'main'
    2 = 'main'
    3 = 'main'
    4 = ['secondary', 'main']
    5 = ['secondary', 'main']
    6 = ['secondary', 'main']
    music = ['secondary', 'main']

# Gaps
    [gaps]
    inner.horizontal = 8
    inner.vertical = 8
    outer.top = 8
    outer.bottom = 8
    outer.left = 8
    outer.right = 8

# Key Bindings
    [mode.main.binding]
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-m = 'workspace music'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-m = 'move-node-to-workspace music'

    alt-tab = 'focus-monitor next'
    alt-shift-tab = 'move-node-to-monitor next'

    alt-f = 'fullscreen'
    alt-e = 'layout tiling floating toggle'
    alt-r = 'mode resize'
    cmd-q = 'close --quit-if-last-window'

    [mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    escape = 'mode main'

# Window Rules
    # Godot
        [[on-window-detected]]
        if.app-id = 'org.godotengine.godot'
        if.window-title-not-contains = 'Godot Engine - '
        run = 'layout floating'

        [[on-window-detected]]
        if.app-id = 'org.godotengine.godot'
        if.window-title-contains = 'Project Manager'
        run = 'layout floating'

    # Blender
        [[on-window-detected]]
        if.app-id = 'org.blendernetwork.blender'
        if.window-title-contains = 'Render'
        run = 'layout floating'
